require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(password)
  Digest::MD5.hexdigest(password)
end

task :test do
  puts "Executando uma tarefa de teste"
end

task :local_seeds do

  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))


  users = [
    { name: "John Wick", email: "john_wick@gmail.com", password: to_md5("k1llth3m4ll") },
  ]

  MongoDB.new.drop_database
  MongoDB.new.insert_users(users)

  sh "cucumber"
end

task :hmg_seeds do

  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))


  users = [
    { name: "John Wick", email: "john_wick@gmail.com", password: to_md5("k1llth3m4ll") },
  ]

  MongoDB.new.drop_database
  MongoDB.new.insert_users(users)

  sh "cucumber"
end
